name: Secrets
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set secrets
        run: |
          echo "OPENAI_API_KEY=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" >> .env

      - name: Build
        run: |
          echo "API key: $OPENAI_API_KEY"
